server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Cấu hình này giúp React Router không bị lỗi 404 khi tải lại trang
        try_files $uri $uri/ /index.html;
    }
}
